vim.cmd([[
  ab jjcheck ✓
  ab Ironcore IronCore
  ab Hubspot HubSpot
  ab jjheart ♥
  ab jjcomm ⌘
  ab accidant accident
  ab accomodate accommodate
  ab accross across
  ab acheive achieve
  ab accomodate accommodate
  ab acomodate accommodate
  ab andthe and the
  ab apparant apparent
  ab aquisition acquisition
  ab assistent assistant
  ab asthe as the
  ab atthe at the
  ab beutiful beautiful
  ab cemetary cemetery
  ab changeing changing
  ab convertable convertible
  ab defendent defendant
  ab embarass embarrass
  ab equivalant equivalent
  ab guage gauge
  ab harrass harass
  ab hte the
  ab teh the
  ab judgment judgement
  ab liason liaison
  ab lieutenent lieutenant
  ab performence performance
  ab permanant permanent
  ab questionaire questionnaire
  ab recieve receive
  ab relevent relevant
  ab rythm rhythm
  ab seperate separate
  ab shouldnt shouldn't
  ab couldnt couldn't
  ab supercede supersede
  ab taht that
  ab threshhold threshold
  ab tomorow tomorrow
  ab transfered transferred
  ab vacume vacuum
  ab wierd weird
  ab wouldnt wouldn't
  ab independant independent
  ab independance independence
  ab occured occurred
  ab occurence occurrence
  ab occurance occurrence
  ab occurrance occurrence
  ab reccomend recommend
  ab reccommend recommend
  ab monday Monday
  ab tuesday Tuesday
  ab wednesday Wednesday
  ab thursday Thursday
  ab friday Friday
  ab saturday Saturday
  ab sunday Sunday
]])
